//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoWebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGTHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGTHUC()
        {
            this.YEUTHICHes = new HashSet<YEUTHICH>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDDANHMUC { get; set; }
        public string TENCONGTHUC { get; set; }
        public Nullable<System.DateTime> NGAYDANGTAI { get; set; }
        public string NGUYENLIEU { get; set; }
        public string HINHANH { get; set; }
        public string NOIDUNG { get; set; }
        public string NOIDUNGPHU { get; set; }
    
        public virtual DANHMUCCONGTHUC DANHMUCCONGTHUC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YEUTHICH> YEUTHICHes { get; set; }
    }
}
