//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoWebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHMUCCONGTHUC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DANHMUCCONGTHUC()
        {
            this.CONGTHUCs = new HashSet<CONGTHUC>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDTAIKHOAN { get; set; }
        public string TENDANHMUC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGTHUC> CONGTHUCs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
