//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoCaoWebNangCao.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YEUTHICH
    {
        public int ID { get; set; }
        public Nullable<int> IDTAIKHOAN { get; set; }
        public Nullable<int> IDCONGTHUC { get; set; }
    
        public virtual CONGTHUC CONGTHUC { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
